In [1]:
import torch
from torch.functional import F
from torch.distributions import Normal

def quotient_distribution_1(mu_1, logvar_1, mu_2, logvar_2):
    var_1 = logvar_1.exp()
    var_2 = var_1.detach() + F.softplus(logvar_2.exp() - var_1.detach())
    var = 1 / (1 / var_1 - 1 / var_2)
    mu = var * ((mu_1 / var_1) - (mu_2 / var_2))

    return mu, var.log(), Normal(mu, var.sqrt())

def quotient_distribution_2(mu_1, logvar_1, mu_2, logvar_2):
    var_1 = logvar_1.exp()
    var_2 = var_1.detach() + F.softplus(logvar_2.exp() - var_1.detach())

    # Convert var_1 and var_2 into covariance matrices
    A = torch.zeros(var_1.shape[0], var_1.shape[0])
    B = torch.zeros(var_2.shape[0], var_2.shape[0])
    diagonal = torch.arange(var_1.shape[0])
    A[diagonal, diagonal] = var_1
    B[diagonal, diagonal] = var_2

    # Invert A and B
    A_inv = torch.inverse(A)
    B_inv = torch.inverse(B)

    D = torch.inverse(A_inv - B_inv)

    d = D @ ((A_inv @ mu_1.unsqueeze(dim=1)) - (B_inv @ mu_2.unsqueeze(dim=1)))

    beta_1 = torch.det(B) / torch.det(B - A)
    std = torch.sqrt(torch.diag(B - A))
    beta_2 = 1 / Normal(mu_2, std).log_prob(mu_1)
    beta = beta_1 * beta_2

    return d, D, beta

In [2]:
mu_1, logvar_1 = torch.tensor([1.0, 2, 3]), torch.tensor([1.5, 1.25, 5])
mu_2, logvar_2 = torch.tensor([-3.0, 10, 1]), torch.tensor([1.75, 20, 10])

log_probs = torch.tensor([[1, 2, 3], [4, 5, 6], [8, 9, 10.5]])

mu, logvar, normal = quotient_distribution_1(mu_1, logvar_1, mu_2, logvar_2)
d, D, beta = quotient_distribution_2(mu_1, logvar_1, mu_2, logvar_2)
D_log_diag = torch.log(torch.diag(D))

print(mu, logvar)
print(d, D_log_diag)

log_prob_1 = normal.log_prob(log_probs)
D_sqrt_diag = torch.sqrt(torch.diag(D))
log_prob_2 = beta * Normal(d, D_sqrt_diag).log_prob(log_probs)

print(log_prob_1)
print(log_prob_2)

tensor([12.7956,  2.0000,  3.0136]) tensor([2.8734, 1.2500, 5.0068])
tensor([[12.7956],
        [ 2.0000],
        [ 3.0136]]) tensor([2.8734, 1.2500, 5.0068])
tensor([[-6.2866, -1.5439, -3.4223],
        [-4.5413, -2.8332, -3.4522],
        [-3.0054, -8.5633, -3.6099]])
tensor([[3.9100, 6.6411, 2.5158],
        [1.5354, 1.0316, 2.3360],
        [1.9021, 2.4314, 2.4261]])
